Blog devise
Estherstarr/Blogs pull request #9
Opened 2023-02-02 14:33 UTC by Estherstarr

In this PR, I implemented the following 
- [ ] Remove the `current_user` method in the `ApplicationController`, devise will provide us with one.
- [ ] Install and set up devise](https://github.com/heartcombo/devise#getting-started).
  - Can register a new user.
  - User logs in with a combination of email and password.
  - Hashed passwords should be stored in the database.
  - Ask for confirmation by email.
  - Can reset password.
- [ ] Modify the views in devise

2023-02-02 15:00 UTC, GzimAsani requested changes
### Hello @Estherstarr and @Elijahdre                     :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with adding devise:+1: 

 ## Required Changes 
- [ ] Check the comments below :arrow_double_down: 


 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-02 15:00 UTC, GzimAsani commented on app/views/devise/sessions/new.html.erb
> +
- [x] You have a syntax error here, kindly fix it 
![image](https://user-images.githubusercontent.com/62705947/216354296-aa65d7f0-a409-49ea-b1a1-a4527c3f872b.png)

2023-02-02 15:00 UTC, GzimAsani commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
- [x] `:confirmable` needs to be enabled in the user model (`user.rb` file) 
![image](https://user-images.githubusercontent.com/62705947/216355411-3f8b5da9-b57a-44f3-a77c-f698cc0c8f3c.png)

2023-02-02 15:00 UTC, GzimAsani commented on app/views/devise/sessions/new.html.erb
> +
- [x] You have validations that need the name but it is not present on the form, kindly add it 
![image](https://user-images.githubusercontent.com/62705947/216356525-8095c19e-7533-4711-956a-4bfabf8e4cd9.png)

2023-02-02 15:00 UTC, GzimAsani commented on app/views/devise/mailer/reset_password_instructions.html.erb
> +
- [x] I am getting an error when trying to reset the password kindly check into that. Also it would be good to have a button to logout for a user
![image](https://user-images.githubusercontent.com/62705947/216358449-79984a14-b97b-451e-bea1-0dd59b0a6b5a.png)

2023-02-02 15:00 UTC, GzimAsani commented on app/views/devise/sessions/new.html.erb
> +    class: "w-full  shadow appearance-none border rounded" %>
- [x] Placeholder should be email not username

2023-02-03 16:06 UTC, Danieldotcomcoder approved these changes
Hello @Estherstarr , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 👍 👍 😄 👏 

Congratulations! 🎉 🎉 🎉 

## Highlights

- Linters are setup correctly ✔✔
- Clear and nice code ✔✔
- Everything is working fine ✔✔ 
![comp-2](https://user-images.githubusercontent.com/87448628/159119684-e86473c4-9b60-43a3-90f2-54048e841394.gif)
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-03 16:38 UTC, merged